### ISSUE TITLE
Sound stops upon opening Friends menu or Gamemode selection menu

### ISSUE THREAD

**Issue by tylerfrankel** [ApertureC/Fortnite-Music-Changer#11]
I don't know much about C#, but I have Visual Studios and could be of basic assistance in fixing this. The music stops playing if you click on the |+| button to search for friends in game, or if you attempt to change the mode from what it is in the selector. This could probably be fixed by asking for 2 additional screenshots for the program to use to know to play the music; one of each of the screens I described. Its been a couple years since I worked with C# and I never learned more than basics, so I could not really comprehend which part of the program takes the screenshots, which part determines where they save, and what tells the program to load them for comparison upon start. If I knew I would have tried to edit. BTW sorry that this was stolen by FNBRleaks it looks like a lot of work went in to this and its a cool program.

**Comment by ApertureC** [comment]
The reason why it stops when you click "+" is because the X in the top right is grey instead of white, so doesn't play, also the blur messes up all the other points.

Game mode selector should work unless you're in stretched.

I'd work on this if I could, but I don't want to waste my time - As soon as fortnite releases the OG music this program will be left in the dust and all work (august (me trying to one up fnbrleaks) + a bit more) will be for nothing, I don't really want to work on it and waste more time.

Also I wouldn't recommended trying to add to it, the code is very poorly made (This was my first c# project) and has no comments at all, so will be very hard to understand. I'd refactor it but, as above it isn't worth the time)

I mean if you _really_ want me to do it then sure.

**Comment by RayanObei** [comment]
how do you play fortnite on here where is it
