### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Traxz12399** [ApertureC/Fortnite-Music-Changer#3]
So I've been using v2.0.0 of the Fortnite Music Changer and for some reason Fortnite starts to stutter. I think it is because of a file called ScreenCapture that will continuously appear and disappear in the the BitmapReturn file. Please help. TY

**Comment by ApertureC** [comment]
Yeah I did expect this to happen tbh, every 0.25 of a second it checks the screen - not efficient!. You need somewhat of a beefy pc to run it. I'll try putting the code back into the main program (desktop duplication variable would always cause errors when in the main program).

Putting it into the program will allow it to run faster since it'll be in memory instead of on the hard drive (hella slow for this case).

**Comment by ApertureC** [comment]
I've (finally) found a fix to the issue. I'll release it in a bit.

**Comment by ApertureC** [comment]
holy crap I was watching summer skirmish when it started lagging, checked the thing since I had it accidentally on. 6GB of memory used lol, I think we have a memory leak.

**Comment by ApertureC** [comment]
absolutely no idea what's going on with this memory leak. I know it's to do with the screenshot method but nothing else :| I'll take a look again tomorrow.

**Comment by ApertureC** [comment]
Solved! I'll get it out soon.
The disposing of the variables was too far in to the method, so moving it out to the end, and making the bitmap return at the end part seemed to fix it for a reason that's doesn't make sense to me at all.

**Comment by ApertureC** [comment]
never mind more memory leaks - it's minor and isn't going to hit 6GB of memory in 30 seconds but it still needs fixing.

**Comment by ApertureC** [comment]
Fixed with latest release! Reopen issue if it isn't.

**Comment by ApertureC** [comment]
Pulled release for being buggy as f

**Comment by ApertureC** [comment]
I like how I just pulled the release because my browser had the correct colours open to play title menu :|
